[2025-05-06T13:32:22.644+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-05-06T13:32:22.250962+00:00 [queued]>
[2025-05-06T13:32:22.649+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-05-06T13:32:22.250962+00:00 [queued]>
[2025-05-06T13:32:22.649+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-05-06T13:32:22.649+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-05-06T13:32:22.649+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-05-06T13:32:22.655+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2025-05-06 13:32:22.250962+00:00
[2025-05-06T13:32:22.657+0000] {standard_task_runner.py:55} INFO - Started process 21931 to run task
[2025-05-06T13:32:22.659+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2025-05-06T13:32:22.250962+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpte54m4ay']
[2025-05-06T13:32:22.661+0000] {standard_task_runner.py:83} INFO - Job 46: Subtask create_table
[2025-05-06T13:32:22.690+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2025-05-06T13:32:22.250962+00:00 [running]> on host 081a24b4289c
[2025-05-06T13:32:22.718+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-05-06T13:32:22.250962+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-06T13:32:22.250962+00:00
[2025-05-06T13:32:22.722+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-05-06T13:32:22.724+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2025-05-06T13:32:22.724+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2025-05-06T13:32:22.728+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20250506T133222, start_date=20250506T133222, end_date=20250506T133222
[2025-05-06T13:32:22.761+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-05-06T13:32:22.774+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
