[2025-05-06T12:32:44.814+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-05-06T12:32:43.974296+00:00 [queued]>
[2025-05-06T12:32:44.818+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-05-06T12:32:43.974296+00:00 [queued]>
[2025-05-06T12:32:44.818+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-05-06T12:32:44.818+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-05-06T12:32:44.819+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-05-06T12:32:44.824+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2025-05-06 12:32:43.974296+00:00
[2025-05-06T12:32:44.826+0000] {standard_task_runner.py:55} INFO - Started process 18876 to run task
[2025-05-06T12:32:44.828+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2025-05-06T12:32:43.974296+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp4s33ie5y']
[2025-05-06T12:32:44.829+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask create_table
[2025-05-06T12:32:44.860+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2025-05-06T12:32:43.974296+00:00 [running]> on host 081a24b4289c
[2025-05-06T12:32:44.891+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-05-06T12:32:43.974296+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-06T12:32:43.974296+00:00
[2025-05-06T12:32:44.895+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-05-06T12:32:44.897+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2025-05-06T12:32:44.897+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2025-05-06T12:32:44.901+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20250506T123243, start_date=20250506T123244, end_date=20250506T123244
[2025-05-06T12:32:44.926+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-05-06T12:32:44.934+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
