[2025-05-06T13:17:38.232+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-05-06T13:17:37.071954+00:00 [queued]>
[2025-05-06T13:17:38.236+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-05-06T13:17:37.071954+00:00 [queued]>
[2025-05-06T13:17:38.236+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-05-06T13:17:38.236+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-05-06T13:17:38.236+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-05-06T13:17:38.241+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2025-05-06 13:17:37.071954+00:00
[2025-05-06T13:17:38.244+0000] {standard_task_runner.py:55} INFO - Started process 21175 to run task
[2025-05-06T13:17:38.246+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2025-05-06T13:17:37.071954+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpkoov87ck']
[2025-05-06T13:17:38.246+0000] {standard_task_runner.py:83} INFO - Job 41: Subtask create_table
[2025-05-06T13:17:38.272+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2025-05-06T13:17:37.071954+00:00 [running]> on host 081a24b4289c
[2025-05-06T13:17:38.298+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-05-06T13:17:37.071954+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-05-06T13:17:37.071954+00:00
[2025-05-06T13:17:38.302+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-05-06T13:17:38.303+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2025-05-06T13:17:38.304+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2025-05-06T13:17:38.307+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20250506T131737, start_date=20250506T131738, end_date=20250506T131738
[2025-05-06T13:17:38.346+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-05-06T13:17:38.360+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
